# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avm < Formula
  desc "A lightweight local/global command alias manager"
  homepage "https://github.com/DracoRunner/avm"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PrajaNova/avm/releases/download/v0.2.3/avm_darwin_amd64.tar.gz"
      sha256 "9687212d7cddd6a52c70b909402852984f410b91c436ce76852f6218a342dc75"

      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PrajaNova/avm/releases/download/v0.2.3/avm_darwin_arm64.tar.gz"
      sha256 "ccc8c833cddd2432c1d7a0fef61d7d894aea41b53780cba7763e7d61b624efaf"

      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PrajaNova/avm/releases/download/v0.2.3/avm_linux_amd64.tar.gz"
      sha256 "bedaae5f6abde72603d1ca0d8e530ac01cd65006e819ad0e989e5e3ffc0c2c6b"
      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PrajaNova/avm/releases/download/v0.2.3/avm_linux_arm64.tar.gz"
      sha256 "31208482a9e2e99ec6c38081417eab904205670828dbc7986b0dcc31be6e1b10"
      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
  end

  def caveats
    <<~EOS
      To enable avm in your shell, add this to your ~/.zshrc or ~/.bashrc:

        eval "$(avm-bin shell-init)"

      Then reload your shell:

        source ~/.zshrc  # or source ~/.bashrc
    EOS
  end

  test do
    system "#{bin}/avm-bin", "version"
  end
end
