# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avm < Formula
  desc "A lightweight local/global command alias manager"
  homepage "https://github.com/DracoRunner/avm"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PrajaNova/avm/releases/download/v0.2.6/avm_darwin_amd64.tar.gz"
      sha256 "c6d9fd4863209dc014a9ea4f97fc18badb901bd7bcb7b2e497aa587988053ec8"

      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PrajaNova/avm/releases/download/v0.2.6/avm_darwin_arm64.tar.gz"
      sha256 "10565f75e54bd5e11328005c85e548d422c64c7ae16e0623200e8190afe4b7f0"

      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PrajaNova/avm/releases/download/v0.2.6/avm_linux_amd64.tar.gz"
      sha256 "65363db05bcfa4466e05090b795305a3be8b09835bf49146c0f1cdb9c1075608"
      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PrajaNova/avm/releases/download/v0.2.6/avm_linux_arm64.tar.gz"
      sha256 "883a24839211b422a5a64e275daada9e6beafac3313faf3b61ac06c722ae21a3"
      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
  end

  def caveats
    <<~EOS
      To enable avm in your shell, add this to your ~/.zshrc or ~/.bashrc:

        eval "$(avm-bin shell-init)"

      Then reload your shell:

        source ~/.zshrc  # or source ~/.bashrc
    EOS
  end

  test do
    system "#{bin}/avm-bin", "version"
  end
end
