# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avm < Formula
  desc "A lightweight local/global command alias manager"
  homepage "https://github.com/DracoRunner/avm"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DracoRunner/avm/releases/download/v0.2.2/avm_darwin_amd64.tar.gz"
      sha256 "728d8f3ec0562183e5cdacc399e8702946d76324edf1a9863a009a9fbba99217"

      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DracoRunner/avm/releases/download/v0.2.2/avm_darwin_arm64.tar.gz"
      sha256 "66603478ab220fffcf6715311c734b839c19327df4e10ac0313971192e0a79f3"

      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DracoRunner/avm/releases/download/v0.2.2/avm_linux_amd64.tar.gz"
      sha256 "deb04a9208a02f3bedb53f0b277b2db7f747bcfd786344552d38c0a9fdb4a1b8"
      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DracoRunner/avm/releases/download/v0.2.2/avm_linux_arm64.tar.gz"
      sha256 "22f4be69fc19be868fd4d736ffd9ffc784656e6a6fd487e4fde8b1d881d46ba9"
      define_method(:install) do
        bin.install "avm" => "avm-bin"
      end
    end
  end

  def caveats
    <<~EOS
      To enable avm in your shell, add this to your ~/.zshrc or ~/.bashrc:

        eval "$(avm-bin shell-init)"

      Then reload your shell:

        source ~/.zshrc  # or source ~/.bashrc
    EOS
  end

  test do
    system "#{bin}/avm-bin", "version"
  end
end
